import { initializeApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Note: In an AI Studio environment, the firebase-applet-config.json 
// is usually generated by the set_up_firebase tool.
// If it's missing, we use dummy data for initialization to prevent crashes,
// but real database operations will require the actual configuration.

/* @ts-ignore */
import firebaseConfig from '../../firebase-applet-config.json';

const app = initializeApp(firebaseConfig);
export const db = getFirestore(app, firebaseConfig.firestoreDatabaseId);
export const auth = getAuth();
